# Generated by Django 4.1.7 on 2023-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0010_card_are_carditems_collapsed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='https://billenium-b-cglx2hn74q-uc.a.run.app/media/generic-avatar.png', max_length=200),
        ),
    ]
